### ISSUE TITLE
テスト用Docker環境の整備

### ISSUE THREAD

**Issue by pyonkichi499** [pyonkichi499/fastapi-load-test#7]
## 目的 (Goal / Why)

- PostgreSQLテストを含む完全なテストスイートを、開発者全員が一貫した環境で実行できるようにする
- CI/CDパイプラインでの自動テスト実行を可能にする
- テスト環境の構築・管理を簡素化し、開発効率を向上させる

## 背景 (Background / Context)

- 現在、RDBアクセス機能（PostgreSQL, SQLite対応）は実装済み
- SQLiteテストは自己完結型で動作するが、PostgreSQLテストは外部環境に依存
- PostgreSQLテストは`POSTGRES_TEST_ENABLED=false`でスキップされる設定になっている
- 開発者が個別にPostgreSQLを用意する必要があり、環境差異によるテスト結果の不整合が発生する可能性

### 必須項目
- [ ] **テスト用Docker Compose設定**: `docker-compose.test.yml`を作成し、PostgreSQL 15のテストコンテナを定義
- [ ] **テスト環境変数設定**: `.env.test`ファイルを作成し、テスト用のDB接続情報を定義
- [ ] **テスト実行スクリプト**: PostgreSQLコンテナの起動からテスト実行、クリーンアップまでを自動化するスクリプトを作成
- [ ] **README更新**: テスト実行方法をドキュメント化

### 推奨項目
- [ ] **CI/CD設定**: GitHub Actionsでの自動テスト実行設定を追加
- [ ] **Makefile作成**: `make test`, `make test-postgres`などの便利コマンドを提供
- [ ] **テストカバレッジ設定**: pytest-covを使用したカバレッジ測定の設定

### Docker Compose設定
```yaml
# docker-compose.test.yml
services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser  
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5433:5432"  # 本番環境と競合回避
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data  # 高速化のためインメモリ使用
```

### 環境変数設定
```bash
# .env.test
POSTGRES_TEST_ENABLED=true
CI_POSTGRES_HOST=localhost
CI_POSTGRES_PORT=5433
CI_POSTGRES_USER=testuser
CI_POSTGRES_PASSWORD=testpassword
CI_POSTGRES_DB=testdb
```

### テスト実行コマンド例
```bash
# PostgreSQLテストを含む全テスト実行
./scripts/run-tests.sh

# SQLiteテストのみ実行（Docker不要）
pytest tests/database/test_accessor.py
```

## テストに関する考慮事項 (Testing Considerations)

- **隔離性**: テスト用DBは本番環境から完全に分離
- **再現性**: 全開発者が同一環境でテスト実行可能
- **高速性**: tmpfsを使用してI/O性能を向上
- **クリーンアップ**: テスト後のリソース自動削除
- **ポート競合回避**: 本番PostgreSQL（5432）と異なるポート（5433）を使用

## 期待される成果 (Expected Outcome / Acceptance Criteria)

- [ ] 開発者が`docker-compose -f docker-compose.test.yml up -d`でテスト環境を起動できる
- [ ] `POSTGRES_TEST_ENABLED=true pytest tests/database/`でPostgreSQLテストが実行される
- [ ] CI/CDパイプラインでPostgreSQLテストを含む全テストが自動実行される
- [ ] テスト実行後、Dockerリソースが適切にクリーンアップされる
- [ ] 新規開発者がREADMEを見るだけでテスト環境を構築・実行できる

### セキュリティ
- テスト用の認証情報はハードコードせず、環境変数で管理
- 本番環境の認証情報と明確に区別

### パフォーマンス
- PostgreSQLコンテナはテスト専用のため、永続化不要
- tmpfsを使用してディスクI/Oを削減

### 互換性
- 既存のSQLiteテストには影響を与えない
- PostgreSQLテストのスキップ機能は維持

### 運用
- Docker環境がない場合でもSQLiteテストは実行可能
- テスト用コンテナのリソース使用量を最小限に抑制

## 関連Issue

- 元Issue: #3 RDB アクセス機能の実装（完了済み）

## 優先度

**Medium** 
- 機能は完成しているが、開発体験とCI/CDの改善のため

## ラベル

- `enhancement`
- `testing`
- `docker`
- `infrastructure`
